apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: musclecode-prod

resources:
  - ../../base
  - ./secrets/sealed-app-secret.yaml
  - ./secrets/sealed-db-deployment.yaml
  - ./secrets/sealed-registry-secret.yaml

patches:
  - target:
      kind: Cluster
      name: postgres-db
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod
      - op: replace
        path: /spec/storage/size
        value: 20Gi
      - op: replace
        path: /spec/bootstrap/initdb/database
        value: musclecode-prod
      - op: replace
        path: /spec/bootstrap/initdb/owner
        value: musclecode_user

  - target:
      kind: Deployment
      name: musclecode-backend-main-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod

  - target:
      kind: Service
      name: musclecode-backend-main-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod

  - target:
      kind: Job
      name: prisma-migrate
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod

  - target:
      kind: VirtualService
      name: istio-musclecode-backend-main-service-virtualservice
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod
      - op: replace
        path: /spec/hosts/0
        value: "api.musclecode.io"

  - target:
      kind: ConfigMap
      name: musclecode-backend-main-service-config
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-prod