---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAmMwactff6EVGAQ17hbwwqetzqVDVJkA3poAq+zDmnWM21OPErPcSED76OwEvA1HoaJCTjDJ5QOm/m2secrC4n4WUfcunDlDyRY+cMBrZswhpHMK++XHQmCFN8lRWKsbB0LH94NdGMLnOVkI2iPuPoLfsScRP1nIJMEmbObHXQrlFUlD0wjrok40Dhtn3CA8/pFVqs/mi+WFp0jbQy5m/mkm7IG2cuVI8My/cnTdnkQuaK0BQtpWoPKRUNu9pq+CJIDdWTB78qsvNe4/CGggrdmu6UUp5nTDZSxRF4C1t461KsnjgiWvJCDawIUP3oz+IA1L9ykboczR1xwlz3AlRtrRImKs9W36WHCM4K9Xh4/JrDOxlnO8iXU3RT/WXTsO+xa5fclhMv13rWSdUuZqhApwiLxCtThdxi3VVLHSNzp2WuaQ1pkqju5olLXf/UjyNEC57F616wdBh5+osiLz43ONW+P0blcAY0g60d8+L164mpOxqiNksck9RWqMsW/H0BkxXaQL3Jp45CMzauZ+qkAK5MO4AJf2ipRQNPsr5g0CPZRjPnpXaLeBDx+YBOx/y7PRNUClFKzb9/3UXExhpvNagMyIEDoLVKLXSd628Vy0GgkgmSEAZK5jiGsg+teHiO360OfICxX5NBs/9R9/Pozi4eQHJDUh4We7we02mMVsApYXmmek6X1Tv9eJ2DB9Q3AlvTqmZsXvySk8SLIkaKCE/kinLxylggebLL1Z9BQoVdjIrpAnPjL0aIbVadpSyVRfRw6nHK1TbZYjS3KmUZz9gb6xiX/jao3cRCOjeRHVB8+A3//AMr1QbtPQS8SgEXGb3pFD+BHE2PsJ2+l9f1bzwBe0R2bD7pLZp6W460E9bMEvM+XxgJwS3W4jlJsAmN9KxUG1ZDJKF3FUZeuDxdfS7wigHTniOD48MCzehRiJwyx93J
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
