---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBqO8/lx9cr4YfRItVzFlZ1eHqJsMetkW/OnwDeShgnzLvG0CjBsELFSklhWv9oSrgqoJT0aOSB4HvVtefk7bf0dDaMCDnFmteOfA2vHw1+w9EjTYZdGujN6aQF0UoKy4Zdpl/VwbbHZkXklsptDVa48L81yeBDrep9FmNb5gsm484XgCzW2FWS/WVmCytq3UP01mhKA49RblvzMVazVv8ll8fLAIoFIkX/3hbvhaXUquSQogj1c+zKnvHeGHRqXS+3ahj/DdBW0JQHEcHsHsABHx/NgeXGT23rkb/RtS1mrYLT715k+MYY6EEMfNOH2b9jsh3Tml9IPXttaQuPIk2vjh7nGMGEBzgImDTfb1+vNwayMLuaJFtTOnm/WZCR8lh7/sb5+j8q6T5DbbvOGcnUHLBYkCzh/V6mAsLF5sN/5lbt+YQNFoS9uKraiIZAWX3NccShh9yPZ0QCdTQHoxwcbR9lmzJ6HQ07MWeaQkhDPhUnAPptnXhmdubqsoueTCG2RB3fD1t/RDRFzvB7RNMsex9sR6NmF1wv/U7/gj0EpeJ32hIN7vxjbcBW+N39eefs1PKuGP5Whrr/pA12dKUuoC4S2SfOmVab4DbOO6S9Qey33wFO45CJZEd1ca2ewc0+rus54ZI3O1Ypv2LT8BwxpOF4DrgPCPpSZxC/1zrrz3yU0Ewek1J2lptamw0YZEcKu6hc9jzutAb8ksJoIaOfXstGvVucGGt8//iVVtqhj5hSOL6QXjLH5nRozFHgIuR39F6V5t2AZ6Blduhslwo1rA9fJEPTv+2t2bo5a4itxCE16xbfodgEfXyRXRjfDkxuoCvis7HG5Ri/6aIImNKt9b/srVHJgMIbjZ/Jn+lclbc18IJB3cns68FOzCfqSrSEWvgBZS48eiBrikyzOPTcj58Wk2Wz2HgbBIOH0/lCzhhqLebn6zC2mKJYnArEqaY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
