---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCcIWCN1xXN5xOz4gZcgpQudw+bN5ap1cNvSiHa20gAfZhaIZZa1W35ljIJ+ltlAygXOBucQ7DvCZvJhtB1GTLwqnL3PkTgg6qwgcq7bm06edqhjJELeClXcqeTZu9/g4VNVr3pIu9kpWCsu7Tb0sNwsHMz5yCKWNgiK1D8CegxtvmmMa8Pvmsizh00GZrlbW/wD5paCmH2c5TkTj2EvzgalFaUJbARR44NyC/4vgbBWrU6cukqGJ+Zy96Mf877NpgGEsKKygLX3MBWHdH5J6PcrA24GicVm6Lnxe5oa6igZhq8A1dotQOFk+6BaAlX/FBJ+fyJ4Mv8/3yjOVbefy3f26XG/mBK6iscxNX3rvkBGJAzMoN39xE7di3iA9udhOp6gSc6KAAHZYs6H/fxRBR1s8mCUDnniAYWydmnSSlE5g6oCFYr377kGFsTWoUcQTAGoPRs0pznD1ICUPUZZ+V6Acf95X2ScmjN3eks6KE4d4X/kC2Gi8332R2lk7Ok787HcDdrePqk2C9/gWv6oX/wgNf/YEV09IWneykoJPGXRPsWOas93z872IZA/+bW8S9Zyd2whO+2GyuaxvCO73hLHCV2bQwsSTYmZw3sTUclpYbRmqeT+thosMmKHU5U6ao3UZviHMN2qltyI35fCeIVEWjEUfVKKNfxhzv3HXBDYeFqqg2Us3p64Fr/AQkZCFIZ5sSxHyhH4V+SeaJVfRg+LZ5paDd9rUY=
    username: AgAqHzVeYEXyaV0jr22zwLN/gvy+I+Fx4VDmC+UUS/qbPRQgwgFDQ3eZ3SkkbvD9nkThptzTy2z/43JVTm5tZns3G9ieN54ShjcsXcY/lv0CfemQe00anciYPjUiuSkkkAB9NwfDNrZ/AGOvMMMWAV+FEsikhbjyNR1AkCvLjRTxN236BP5T+MJvkvmvz+RaivoAKzjsN++eB9MxwNR8ygT2SPdCT/iVxOyc4cLO805M1Jlc2pqyINReRDuv5x2MrskbYgyTS8H3CIskIxWNMi5QZSrZK05Niz1+1ysaIZWCBxwTi1RERnV24LL0ACRI+e4tF5Qiws8Bv4hviw+eG3YxLThrRyjrvqGGbikZ6fC6ixq7QQ3MC9u6L+/e6t/Ele1LGx+OHmtLkuv0fdI6eGJUUd6Bou/IWRE67kzA7PEr+rNadL9dCQTrFY4w6sCvNmpLA6VUlWuuwUM3PDnktufMq/rwaMfscTLOmnjVuZ4n9Bc4d0d44YN/Q7z5+4bLw409/kyNhJ62GG24hMG9H7aVl07BMHksLynJw0L5VLY5OZz/vOAZ/n3AcR5s6W9v0NBVBeiR9FZ19LuaCIzl2tF0sHPDtzYMeBWSYTCQRXvvvu8jEqsN8JO6IvPluxj9cGpIma7I3v/ru9hvd5YTI7OfaNlgXI10WurJw21smvqFBDZ3pevTwKzrfGmqe5WgyvcvdDnYI5/v4gBF+DTOccU=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode-prod
    type: kubernetes.io/basic-auth
