---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBMXX88St4BNb/x2jNKSwhYf8XVWZTfYuc0qu1sNx2y/48Z/K/0aA+7mu1BzrLF3vekAxvL8yRO6rOwYhgPfiHTnq4+rnKMj9N33Qr2gSRMj1AGt63ZzT2oAWJahji1xKuAFQjK1gss+lXQLZ6YGSjeSjIux+wxmutAHstmLH8/fGIYEMrNEcauxmcF+q4MI5XxULSSRnBuGDnQ8lCNA+yIxickSdSlo/jSUFKMG4z6YOgf+PN46/4N5xfnHlWUD+o2eJpgskYA+e05QXzEGCjle21dxXV8e05JZ9CLcjJqNSIO0v0Ap/SYAS79LGKQH6JCCSUzxtH1dlU3ckvn8qT17wV32Pjpnw22GzXgbXy+9juLBHYNPkoFkfXWnQyXiC5UQ+wM52SDGiUc6IY+ImlDceBZRHR3ic8HGJJUvojpkc9/YCKsKTpeETHygiBbPpfungkkj/j5tdR9AT2JfCmGJXtEcywjEanTnQecrHTNT2mnHF3Ii0pSO+hdpYEw5myHdJY1ll1wUJfMzC4m8p1TRU6LrcfY9LWp0rRxi/hMc9AJlHr+Ug7h6YRzUHstGUMp5ix5k8HKsI9RufP05fxG5ytrupdr6G8Y3SmvgheM8fy/wZDAnpslfKjKIwshDE0vda5v6i8lGyDYzMOVYk5f1ZlH3PnGtTiDCvYKLUdTajICo7D193FhQKqZ6+8701oq/bOZsANV6KQtZgBOsaisO1jYOgg2JXVdt2GHuq/AFmnXlzCXyRpL9ZUzFOvGUtbazXX/TCRXbLqDsubYHe4Aj4RQIbNNDYqrNRZsi+7pCz5YH64NH1nYILs0qYRBdQbN5g0Yqg53BWvip7yUOx5vC7lrOtbtY71eaFkwkrW/Snw7LLrKdHJOivr1U9elFQ1D9HgPn5RXxGusbgictcNbcoXBdRf2hdvzyXA7+ij1JWYB/9QH
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
