---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBKvqNdUPWArJWZKePPDu14JYEylew9Dme4D4vOfCSjeQh0dTxbJOqqkyOsdSrC7IOyP7EUXzk4kaca26aVvXsMphnEWJz0V5crXgSz5I/eG+G2H2+c+xig6suxpyQ9EiwSfRtcu/83E5euuN6SQaQ02LX1tudnQvz0E/6FNHFD9CnWbmo14Bk8UxRXaAbdnm/rzdNQ15oBW75G5tGes7oOUMFrD1f4sf2Wumm/PuqusW98/giXgtoEP6rp1dUxfeUND7WgLqF+bCppU4gRp8e3BNMof8DkxxRe5CME5xk25bvLoxqVRI4Af+3cpW3DtnW2//Ml1vcKiNNIHcMtn4RClriGfl7fymB5Dl9i9Lo62cTDQto+hhMMXi8kYWXpudmU+q91YTacUIf+jVASvVfRB176mSAMU9K7p/LEKwv8oJYX0bM4QDBlV5haJDSzQZoO4MzUVbvBbDaOZCNQ3OAomojdaa7A4IeIZ8+CzBtfBmUIdNzFiKpxYDIunttmbB6lyADQUGA+0r/bldMa/DB105DIg3nXztVooL2icnF89ReEDg2XCeDE/jHwoVRbGBgoYbl4qw8dcZ83ZIqVmwjxcokYfDC0/j1M9MY/dhOENlv2OCuai/9BWFVVTRPHseqGXw+P0l25VD8XXUC9G2Bh5m5n81Wn589R3c4LVivdPlJmYWGJMOFYZyroaDey96cJ33pcMSnaNYdQBNSAQ8zRVM4RB1Xh7Cw=
    username: AgCGQcY2GoC7RK3sNlRcdKBa9uFLv90btjeTM1Bdvlq5B3GHAdmIu2NGGQFGC6+ytMJltzs3CvdBahSRveuqqBM+odrDcXD3P6d4TwUbqutPje13BUixDnCrsxQlr6s+EmmlpakhEsoOfFKocDmXy7+bVTuHMj4P4SsZu65chV8DXhUDSXYBA38d5W6GpzQIDyBcP5WSq+4ueb9BubO0I6FjvsG4PRjsDCb/5Jbn7Zlrvuj/ylY96phoP11TUiEzSYNw4IXikx2MD7qHeEtBhCUn7OvOni5v0h+gnD18rhqYiwGnSjIG8T7I8rFe67HDXAqSYdRdjCAZ54Z5KsAe+lcb51Lg53MRQaxa685XuDlhSkUh0VcH5KME2yahnTNTABg5w94iWYPc0FwFrgDZuRtAON8KJ2yJYsVK0PBUyzLR/64htOk0WFx2nRJjtX0T+iBR4vpvc7eacdVI6HxbrjeCS4j59jwNOGCjR034Qpi0fCfVPkTM5R+u9N9sRKvJ5rYBw77aEWcfGuB+5r/X1lg0fY1UuKbEjYWD6tbWuVvASvl+fIA1QS5D8JBhsQOR7DWv7NXpXMytJiZsB9+3Ot10CEW5exD6rRpmVotGnAGUqGxpwYUAJhR/6RGt58EBcdIst2t2Tt2RDLq0ww1YQ4Te4g/0alkbJZ9jSpMSP9uLsiAD4/lcCJGzjs5sQ9hylWxgIyNvkIWnGImMoqsxjqc=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode-prod
    type: kubernetes.io/basic-auth
