---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBqjmvkUkoobvaYwZQb2mwPkR/DgPs24yNoNv4wvMOOy5ydAcQgal8WXUDl2lU5PIA6wwblMaPlwpoVu5mweIAZ7+BtdWkytOpS19D4DyB4AZ02WAnjbftKmsBmcuu4fxxmEMBBoMdD+hCCurM3fgnM3Ebwz3DGRE3z224XwjpgTaOUNhUZtkJmq6qW9JYqyBwpWXA+wHi+yRGFJWKadmmU1iVR61kclOBAsvt13zHJIahHHoRahQX9hZd/sivlGswJHL3H1kAKzmu5FH09K/0YnYYGz+rCLB+d7d+yTuLwAdsMSC75lgKAglVuVq5M4c82mhnea2A1VYgnwASxkA5hlE3Mb6l3tn7KTZx9PN+kC6MszS0DEXW4kCerRMhan9MKs1AoJeSAcS1jZGFkSQUpTpWNixRccWt0AupE+skdCdS7N/RniMj/CbdzzidXk2OvRLAb/bc4jMvtQFS2w/1dsLyQLcvpslPDpl3JQSjozds+3uta+0ZiAcei3H62tGYrqc8pf1U3EGG1A39UARGYU916zfZala5DoHolWMIJujJ+Kp3JGPPpWXzwEnzOIoy1gFk3i839HcE6WgIJ1jVHH32WMjcb/G3Ea4k73SUrfIfPKceqJvD//88J97M5R6xcVV1KmKiw8LIuFzSp2Qgbfh/cRhHWNb7FClWgVe8sfJZqy7Gm6jwgN2Es9Bq/IjXH5rvaW15M8ycx1kAGnSZm3JGG/RpRBlU=
    username: AgBHyEJ5DUL22e4M7m1HQILep5gEew4wKUqwr27pl99KpjShQQURiNQF4b1d9LajNzMReGs+vF+w3R1OMXl5Zo8Yoka0lKr4X0mqcTwp5uzWnQT8T+pIXQd3r0Ze+VJOQnYF4vSG3rjFJpCOoJXTFzhuQDPcJi3EMG1sO72FksXlUfZsDykAFyb3imd0NNjC8xY+Q7eOkeEVkiiYao0JtcJR4PTufXSGNMKCoyTvPDqGq3mWcW6wGas9+w8DY4fyoGbZSdp4GCVq/Ph2PKcsHcsD12Mw3XnQDJYPbR5QXcyZlDznFEmTXKn5jXz9ntCnjcrYuAKhe4t00qdYoPsGdYwfzb6bybZWr4wnvjocZIZed1lAZlEtvL9hX5XPZARuRL/JuVVJRkK8Y0+cthtPbTJirw8CRO/eM3POyI3kPJa6GoZZdas/GBOXjrmd1wxH+jp6F/THtpaUaihzakt/nHwbOGhUBq60TFGZJw++uCTGpKGNVKfNZo6epYgN0Ywj+xvhYomtc1DtcFaNheOOFxW6Nm4tiyA5ajy3o5WKDixRby+mWvkMnT94CXIDx30T0JxFOJiLqV34T/SG3n0/uba9Zlx3W7g36PrhR7D+BX0tt9QydBhFGQjg3SYV3q1/Y9a4TT+dlHa/wEiITFL2V+LE/B01xsQiMSdJ6HaO2IFWdjJ94uZwnhBysbEpXhVEXxh5nrAu8s+J2HEcb3LXh38=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode-prod
    type: kubernetes.io/basic-auth
