---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAIy3jzzgM+aml+BiylTNoSvOWO4g7TjYM5Rmk42Gj3hpfU9NjvTRD8wfvh8nVV+M+13F+nQ+sdSH3SgFwczSJfd5/Dp6S+aDQcnUVO/9CStAwFZMbDVqIdPzDNEPBfp95kSMaJRh1sMTiQpuKAM5NdqeNsZh99/LJf8GS9pA+MEaKmHWbigPQs9LO8N0ngFC1k9vDGkaGE3qsg0fFyLyUW8f5TLIFAO0hJR6dNZKTtEDYz8LG1HNNuv+OoQc68iriajCjFD6iIGXOxdIlWsgIhPvO7BN42DO3exZBFAmw4IO5TdmR4d5njoSOI3OpX7+wt80id85ho+OE6lcZsvc7o1Kfz1lupe5Uxuqf70UIC3Z70i+ZbxRFTxCs4MYX61yEiDSJ8sjQGRjCCevqu2fsL+4+SGTQgbDpR2WllMBJRRpIFyDE9N76hMRlsGgddlb48dVxdyCnENlzS/QJ94l/l97d7qCy/pFqf0cY0ByDbMs7VDBKfIDKgIt3o0suPYQ+Yg/6zNGw8xdL3uNwqDCKNElNqJjlRWOnxBLWNOHwL49fJKZQNB0RgpSnKlDAVlGHRarO5wnPK8DPztFe20ntm2UW9HAkpaaj+yFpIO3AhBONFLkJS4rraMQVYsUgaJld51z9jjOFcBiBFvhkO3Av2xH3Ht4/BvIje5cEAwBIQExozC4COHFEBJAAhTcDJG3WiQdEPY1WH/m4T0NDUTa8U3GZLTrRzR87wTP0sbhldlu9mkBsATe3eBVqt+KqogvHOR97kmismTeJ/Lqxd9Tu3h0cNmgsKniHbH2zPbg/OkHE17Oo4ccLFZCrG3qrxuvuLevqEjKUDCiwLEBIn5GxYuD0Y5dwj2BpGYkVaxk9cpg31D5LBctKTqqfvTxTW/+XBLZra8FQO8b7YmGoWrsTwDs2jKKGTu2zVwn1XJ8Ot05a5/aVL
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
