---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode
spec:
  encryptedData:
    .dockerconfigjson: AgBe0HX/oQuutg7GDFlQRdpJr/y7N4aIQ3B3WBXFn0ZqosWceFFOwCNdvMtOjB8a7IEDQW/BynVmpQIJ1JB9fNEjtObAF6M/IS66sPDFzVSXtxCETkL4UWH94u5xacXULs2rRFul/BgE8kICdLHctiYgxHrKzjgEOr7OPFjKZqwdyq2yNdBpZXy7JhX9biLAVRXfF/UdnBmGLUDawKn/dYJwn3e1EmPLhrUMCbbS/LwCOvcdUKzEVovBBUQF0Dwli9v6N/qyNKwmv/9D+83vcbaiAzelb6OllOTkhIZy8WihgjE9TarJ2t3lWoQf1UnxPI+3OQKv7j2YuVHfHf5eyISePgReqffsGZAZXwJpTEdQcsGoNg3j9pTpbi+voUE9fS5h49qISjAC108l6EBaz5mTaz07xBl/vqK6DI4BtRl/C6HaV62k/8FKx6q3NDh1e7PVA6KOsFuzaMRhZ86c8gs3c7EjV8yIsQvO6MZcLkuBmsFdDAM3daq1SJMDr14qiPVe/vSckXPzCnkKNc0J5tp6AKQda6hXz52tSLCywlToU+hpTsy5MLmhASMLka0/lbGklSzxZpwXCKmkTY/2SFVHpcnwxiada0/AFpwYgQpygA7p5ELps7EDfXSLvKtKzzA2J6RXdtl9NFYP3KLyih/Y3gdGIisLgvUqvbS2T8ZiRyCSJ+aGZCuG1AzDFMes7+q/CxjeLx2BPeDHi97lCQsBr/m63ORg4l0+aa1j/HZC7rXkCZSL6/LzfsVr4ya0zCiXVijM7JhQi2EQIgOgGap+BFHJS2+DwRem3xU/Orr12R38ayjtDPDF6dTY0TBUAgcTd4//CKq6flCTHWtlWU3dT2BMqdf0fnoDoDBzaz4zpMl9+cadMaAUb2eis+f94XLJnnrkfhNoNLgmBMuk5cMbPwnbDXTtZ8dtDp4Alj5oz0HJFZHn
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode
    type: kubernetes.io/dockerconfigjson
