---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCC1o+SCTf+r2sJuw+UhNkQjQ/ClEJzp5Ku9k8Rxe4zvOF5zVLfJqnnuwJaMarMJ33M+h73ixC6XEPTTnRPjy0cinp7Zqxcg5BW/bb6PHFBQszXhxdsHEQTI1VQV1c9KVXloaxILLNFv9txSwd8q/jmOLN+WhOtUGqyWeswWzSwtSVFfeTC123L1vFteXJ99MWWDZMQHXThMM23iqJiGY5urPCgTaiQVlKNiNGSfJ90DhYYpJ2cR/iR4VwjQcE5oILpKPZHue8HbrlsbTMoM6kYb3YAjG+jqjo+YoQuqyvi1/eyb6yN0GjNnUSLFXl2JoajD0hLKlzYpWBQfMQPsNnfJeCYgNd+llLkQV/YAv3Vu3ykh4h0GyhLXktqwDDjNZeyH075bIH6rZAgcspi1kuU1DtFxRzyRhuiaSs70uKsh+hML9mXrALW0PUSbECEWNUzeGvQWWJMsxdgNGOhm98E04soAuGsmY0VOZ6QYnreWKXM9MIwKZMqnumXqqcBk2cn52XpxwuNnLXvyU5K5ZbddZ+dHt/hp86Pr44zJ5RJt+3mDwZt+E5fuNdQvJHWAqYC/5iHNELUyK+kxGkPoYkePsn4NWdg62Vv4vOYK08IMo6bDoYlq/o5a7iDYSExCtgOH3IpoMm4/gJ2qd/tgFzX21ZLNrB31VTyB6Ck7h5ogXUkKYsUZn6a5j7LoHa45yrXcXOR4b9EdA/aZzzUV+ntApnWEWmIWegHVnqqIVEnA+VWNcd8jGDdSry6u3Xpl2gq5DIxZU5dVvyt25J/dForHr6sOgdeCxzwGTxEUf5d4hXxe0IrmFSOmMi2rhJxTXkp9G4JCt9LG8movs7bBJyJtSJphT8tEzgH08AztiOW1VteWml6tlzw+/Pf3bgoSla6s2NXnTA/YmhvpFJnXGEFqmPov0IjU8BcNxIgz04EvcG3BlGk
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
