---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBsel0CR5qM5IrVIAwfFR0t1JT6DPo98oxDF156x/KrJa8MmaN9UIXJsO8E9fYW11pmJt1tc69wVeaOQVJQJzFwgCuXJB+vR4h0qdWop7iQ+vCS2wKtmNWInUrtOS3xlE1iiPq+WbzRkqbPX6cCfNbrBOEX0usI1zGng2JPluKe1qQMV/hhw2J0gIZHYKkah3c8lY/pSCSpR4vu3fnzGtJO/vyr7XVQsr3tKKxQ4e41+/P7YstTbjyrlYoa0WypTXyNtlKfTn7k5XXUZ/obWGlPJ2Ccd7VSde7PYkpdMOfdkA/vqlkRYQPLaTK607jTsmyJfg+01QJv9sZQD3ydcjJC5Iy3+EN9HfQBlEtYoxm6PUVqoc6xa6huIP4ium+moFoisUf+ucwHIyzap+fsJ9W5s0lhxxEmHFdqgY5j3xyuys+ulPn3QZc8rAA/u0aBAtXrOMYYeMzNRrSaSOc/4lPaFVu5T2E+OuRwl9DBR1L/0GGrXxWZLZ2B4LVIy1TeR/i7/D6QejSKSxa3fP5bGmbY9eCJnzR7AJZYgsUTGugPzh+XbpdZuFhGAvYlXvlZrGvOX9DNwhtanXBYL+cllMQhVbNPM1yyP+hkiIDDT6xo9umtDUUSqjW/GrowhW5PRI4gHqL8e+1Yd8DhuVP4GBTVf6UuVq7LGS5ORgnzwytz1sGtSd1jJ9R1f60zI70gpD0Lvh0cDy2f6YuicDCkkUziq/LbEJwPhYKEtZN6sOW6urJ5GPsv27PfeGaIZramg2cLpaByRNztuRhvOn8Z9tKInsFZ20NmkM1u+qORLo+4Z9FGF6pdFoy5dIxvE94VNuCb6USWVjJCiZpHRmO3LbWGDG0eNQyfsEMraoJGmsGG4hrAp9LPRsXAYl5uywKrwFC2+2LGx37NFUC6gqTe11cyjdxDuRXNrSxVmizE6aUGNMAv84AF
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
