---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgDNg3haZIIrTyACsudRntZAln/K+6GvwiPmqHX65+bQx55FuVMfxO8dtAIwECCI2bF1CX5dfyfHcS3q2FfcAWn1de7g/R4e5mHJvxdhSed0s54L9wHT8idUM1sfCH1lUDTpCocgWWSTrirmkoBhHr4seGGfU9CZ3DjYH9Wy8OBgk6r2wl5BAaTpWrbbb9f90wF55eNPaSEH9jvTKbDe3wEm61czFQXXQ6Vxkp4fdq7ZRN9EEAR8EtQwYT41uaKnTDGzusFEINYpL5GQaZKYewkK2AvTDWMCM4o/BwHen1bFiKQ+UcjlbZ59XVzgKwFvC3OV5IOLl+SzuaWHUL/ieumWrhOU2I6Yi1czVEMZK1mt0qXFAcLZOu2KOuOzbBdmiF66hx7M3m+9TgmrPef6Pc7No5ZQGIcJZWrlDtMkAsmPfG6FlpKWIi9AwcFImURXxsQpmBLwYOJ8E6UocF6eXwPnf0AMHpUD6YbfHAFQpwnDOxl8cGwwR1wexuaT0rlxyV5CkC9QlmibOS4mVLSeUYdisj925uEF0a6YiQXBwbpz5WjtxQtxkYCWlpUK6VQ8WsJ1mEMWhqHJ8PX72w2OZzxDdEMUu4L28a+0m7Kc+UgW6pk+T93VGrJYCBSRMeJm0e5bc8w1EjXLQS3raLbsb+mjhcuoal/gb3KQ52OcL6m0gwhiXv3r+PUyBCY+jPfKc0tNYUH61o7sJIpp2PsCgfITKNAOd+7Gi+nU47rUK0iOJ9/ObmOcqNhUX9It0+KvX0ZHNPHGUA2DTh7EFc0p07L/k2jaX2rXemEoaOSWAwLAVpgfikjb+4fhyKhh/Fi92Sf9NoewWmVBJH9k+RmwrThgDjuNEQMY+ByIKrxUy9QBnO+kc941cQb5RX4gkjniSohysqW0QGdz4IVPQZMCBODgfQcDMTR9lSqvuDpIGTI3QICybZYy
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
