---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCtfRQIJaJuYA9WSZiL738cRC7yPMW/c1IZ0LyBraioZ4x+jYswC0sJCY4wgNJBnRd7NDN8luY7d22hnzJ9tgWRheCfC9eFVZWZb2iu5rv5yMQZ26CWbfDXvEMawVL+q9dm5t7FNhp1yQf4MFWoGAE7FsfBb5gTj73Od+NcWb90Iy/vdwoCwiyLJv0wZcvhlXnWVEnLiGT6IIy++Pv2OW+yPp7XwP6r76Ejy0T1YglR/VPhTTz4ARGclFcY8xOnBSxVsTTk7l4V+LPEmekGtCMi6FfOmgfeM1AD6uY3H/qR6ttp0KQDG6KUDYy0hX0yx1I4A+zuddTP+4/I3jiNlMcdW6M8Bb9M1qdrYrOAD++niLITnqAZdsMCFgL7WMGb+cD14fE5s+1oizobP5/6XOguILZjckdklhsZHnJAmvpojqDpnIHYxWwfx5l5n9/nUufkeGWfc3Q83PR2BR1icbJ5uqL6e6KH1xkoZhONXi2H8p2IYtMTOUU+s6N6WzDM2x9TBmPD1y6DFflP/W3qNj9f8owRg2sCtM5WxHi0yZkY2XfItz4IxMBzgClcxR2+W9Oi8N7X75+aKL75wUQ+xmdPPZGsUeTb8se+OhmFZ5YMF6/B24LsgeaJUxDxnQC0l2FyUGha3b3QUjTkd8KssynSp1yeFFJ5ATDvaGo/zergYoTXtqB7WfaCk7X73WWhal7eCMX7uj/GwswGactbhGvo3AhuIHI3szpnOvzLeDkD0UF5mb+nYvjjwoXSC/I3ThkRgFZck2w5CZleR9SnO4FImK4VpekamRbyoIudHUWwzGlkDaeJbliqhgIVDbh9sdqoJMMdstdevs8sCQWbbdsPESwQ1mo6t1PUvaKAmhadKAXiIdI/Vl6iZ0zPgYBqmvDzDj9DGrjMoBuJ1KHe1/5mNR3tqfvfrvWuxqbKCS5iMntG+W5H
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
