---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
    argocd.argoproj.io/sync-wave: "-5"
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode
spec:
  encryptedData:
    password: AgAMD792Ow6YXPg6w/E6ZrICbbPf0PuW0xFQWc0I7wS8ooUrJ8iJjolT70UF32NjJhZI2jRGcmqduE2r+AGmY0TgCbvXWmsauniFKNCVHzK53h+h1Z/pEp6cwIYRil9/XFvPUDMuT2P+Cdg7DdJ5NFxfAQCM2v7gWvmlnRA8R3yVZrjpIzRdPDfzfkB1PfxWf7YYTcC43H/F3HHpD6YkJanvS5rv0OH65mk8PzGn3gWCeCBwGy7HF69uu03FlrQCWys5CvhOyIiuOvSCcjYObNdY4W8KyJ0cCi/QWvyYdh02l3PyZkSsQkv8WzXZmWvA2cm3IAakU8Qz4w7BdU4g1yBHQKAcSl0bD2KMr7aAc7pbDacy18QbVU+14wDp+Vh3Q+0ljVe1JP6rncc3m24q+2oj3rnxFE1NIjOsR5dvCJMbGu6vZ0dN04+Y7VFn1gksjS4F3jwQa0f50FQOe0DBNow6ysHZOge7U4qdL/aMwgPDWaqL6Ff9xE648ZLB/8UU6Hs/0e1dZ01l9ROpVdm5R5/ThQWQS7Cx5jmADAQPcCopA60j4yhGHSuanCOqCvYV0bpyA2JcB4DNhiB/b4Fixv8E2KQppVWnzfrS3tWYVgsYuaytVxkY4lY5H/JEqYXEY0z3RkgokN446hlUgSFaW5sgVqknyjLvxUaq8X8fFhHWDNVK1/bdXPZ6ZAcXSFecxtDCQHlQOZlkVQ1nVfy1smG0+Z26nSZOikw=
    username: AgAnf9Fmn4yCgRxUa73lhKusqgaG/qoTz4tF/4EIzKAw0XAe+SGI1TYoOfi42l51V4UrmRoyNhVlC6hpbH6CmU09BEAvnknyDgNLPFYLP9STjeyFpHV7eXVWy3+YtDqcP7N0vzCTEfpVWLqF/0IW4b+BGqJ0DAkli1b+Mt/x1bOyiUFtk9Gyal20HaMh8dCQfsA8tLQQ//4b+rt+Kvkf82aAebUvs2zHkN9qpQ3ZWWrCkLOXADt0Q2lnR2+WdFzwI6uDtcQ4pYfubOWKZzfsNVKDlX8aK6kbVd3iKtbakPzr/jJU7gg4txy0YwwPW2X0bFReDpeDiyBY+Oldtn0MDB6ijGzCpOgv7A9mqyoxLF86l3BT/rPBRLIJu6v1nt9jIHGXZYt/H6A2qAkVIgcI+Y9KUnJKq3lCZfVQ4B1Pu80egy+uvRIq7etaLosNw+GyaZ7sWmYV+Eu9h98IthBpPoyRvxdpvszx5bFR9+V7DHjaqwP1Byo2DYhSFRZEVQLtipPkwT7GXpTF7C9WlsT8yVIBVOdszz0KbYGgBCEKGOo3WFzLyTCg1IzPC9LAIZ2ChQU5F6rB8oIkf0bqO54Oi0PBkw9WKsw8OZGOPtx3eGX0jWL9VQlFoHESlsCqaWtawbskylb0hJGVdDyhPS/RSXLXY4W3NEBFKJ9EIFsOLxd6xgVaQbmwNiZ1TDyiHPxfBE+U/p7tnQCSexARbF5ZO8E=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode
    type: kubernetes.io/basic-auth
