---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
    argocd.argoproj.io/sync-wave: "-5"
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode
spec:
  encryptedData:
    password: AgArxWdt81eaTOBjbtObf7QruR1pNoOkUlbo5iqj0pBVWJLFPxcgvYDqFQutuP/HSZOkuY9Rxcj4kjGj98/KxkJ3o+IikuwBgYEUifNvakHQ68nk8EpQ9/xsi99jBP9braXpgEMHvVBFHFt64BNPgdvivjrpmoa8qb7M/nmt2elvN1K01ruoRUC0I4DYOoorS5l+vYsE8WfQH36hf3fjDCPc+q7ZCUHdNUlsN/NTR2TdIzNxtfRpsq5Str/XMZWi55Hbd759HcOtL0Tvby17Rmtn0IKk6NM7E72+JUsOIlnUnehwIxoi3HvdAiX9AQcurIWNWU4J20xyLSAzkT4AiWFLLZtgn163KRrZ2OYRzNQJzxP9/KX8J/sx7sSq6GdfR/4ALD54bHnFMKg1CA8aN9ENdee+NxaxMs8OUOH68D0zyxflce8T8oPMULpdcP+aYNwsyDhMrObj3nat6vYiJGA71ViCJXlj2qqT+NfY6vxpIRyCoXsXmOeqCXz3bDIIGI2gy3wNZ8qjSDHnd5QTY0bGw8y1nOdAVHQ9+EnXAoQZ3bze0BTY78DAP+YF/9zkPId5TBxHxFe/8XGrai1zuvSXshHu/92RxTmZA73Bv2K7oOR/GAUGbk27LIVw0GJN6H6/Xnogq5Lasjal+vqRmx/VkAwrcdllF0bLGVTPMFyUMJDY8OnfZ9uyPk9atpVz+BKWe1wjlFja0SQqibC+THjXnWyicH+cvBE=
    username: AgCiTLg8+AFtWk81p3u9BhgxOGpGiN46hHMQp3NYrnbuCry17etXgQwpo4oXLvWGSBlrKsDvoeXFDkENXUvk+Jn3I1kG3rwkz9lb6yfgRmzE7afdBN8jVZN+aboyUQvXuX1wNFppSNy76eD023LdZSZNq7XR4OQ4H0coQC1evf+z68V8xnLqC+8HBk+obhppk9zP97BFL1XYCVtfL4kPfiIxyIUWbqTDUjwjawX3Tld11JT4dkE9F8l5Cu8OSZPoZqEPkzbXfcttP1D6LzKMsc+QNzb2AQ0J3CKgDEQXG7X/CW4d3lBhEim9NfaYnOMrHlbax08iCCl3s8+QnPbyXTWUv9ET0Z2Qf7c4VHvcMy79LFITisa5Lj4pYtUmTy/uBawynrjQfbg0U72nu7bG3J1/NgrE7fnBM4nKLyxmIOvu7o4eC4PCJhWmTFTn9QMdRsJcHxs5vD6GJid7Kmqu6eQFNJm5kxu/0veRe+kIo/8MlVkc1174rIdKUlnI/Z9O3E59aOL9JSsBb0T67yz/bL9C+nKSqiUzAWP450S8XiM6nCfKo49L9GgCoWaZVyyeRUJK7amPRf6mSX28cn5o1xoyPDd1DCOmmUpBJyxq8xRlmV0znIIsrypUNer+WaGzoSyQiHJzOoeetPu/KRh3jejRw6QUmzqehmvz6jvXn7odEfcyUUIXN4V+35eCFfsDauozqR+44CpT1nHUrA5P4OQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode
    type: kubernetes.io/basic-auth
