---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCYNzp70s/ekEr/PNNmfwoyCqq3A72McnGbabn9V6Yx8k6F6DKPbk36hcuG9YFVRM9WLHNKAh9yXqF1A6YQmiRDKIDAY0YSEufKTe8JpsxrnZYDMTxrUtMNt8qWjocgW0u96oL1luA6bBvmnF+8DH4T4mxj9uPXfAOAQoRtwfiqS6uYXyJb7AqRSXWTZ+XkvlXfzkF0jlsYE5xnUxMjQtmZbHeaeKdt6n6xiAevvsjXT9893eMa8PiOnthJQOLIl/KEMNfIV9hMjM40U7tGqLpqEFP6v4sA+/nQQvvJmBF4GQJvM/EC9QjMXWeJk3LFps+2frAF40pIiYSaqJIuWND6VBSG+kekSxG9ptC/mVd8k9sObhQImyC86kq8o6w0YhBDsR308pyEqblVOwM2LahorNgWQtF9iSaugW11wC4gEKtx8UtgPbzgcxbMWjzShpsewTnL5tdLgYCS8mWLb492zwnFKRlD/Tcsddnn3uAuYtIO68SwKNMzehnmSZoFjw1voSJeATEFkqIX/JS3SzkwSnsKY5t4YvL6EaQpB57LrLHt7NnYdU16url8qJfdC1PPdfL1VtJbLQO7j69ExiBvaM5Bs50B19Y6e41ACiP/TyW4m9721fSV4U1e3qwmJIRNy+y+THg9CMELWpJeRNjfujy9Kb2OExf41+iuOM3pmI+91jC4/fKMys+xMaAhdVIeoVAMzp/aeCRgPnlV2GxuIK4qzfjUm5c=
    username: AgCJpSWFQiNUAFjpOW7UJm/RZ0GxC1JbLW9rr0aC2vYwqvJU02g7TMXVg/l7p8ooSSDYyZ7aNOWf6xDEXTnP2yPYDr6ImxH+FEk1AQcGifRnG4yrrPCI5bIQwVPkWrm/3p+RfkO3GiNdTh5k6kcLf0o0CW/pUvNHyXojAbtA1L2d3LmUOOuZWV1urQR6KGqDrrZ43iOmxcbfvWaYgwCnvaDcXoLRB+srL3Q2jb59cxD5k2kf+JYoOM5uP4zik+4s2b54AEmp8037nIN+BRsqo2bWw4SiStGxRv7cN59eU9ow4yJ1I0CuBpjg4x1qQmrc8c63NSL9KosMw8syG1q74VhF2nbrHgod/8fcHoUhzxACviHpt+k6XfCd6oOtli/+bKsz8sPoGC2nNt1P2BH4AepstNedxc8OXQrRevtUH9IVRB94phVZ9QKFs1KyXdJHEYnwy7mL5PV0Kq/aDUOS6bn6qd9/S1Md01UYPFAtPJ4SZd3TzaN4hjQl1Y0RWTzQ5TZbBTDHFkh1a66pN748/h9qSsFGg/mWpekMV+xCOkv+cwyQNClFCU/3W2VX2F+0NqF/uHvaDaHK7Cf04SfB6E8eQ7RzEocYX7gkqnStSPN7MseUKlU791RTLqQN9tBorzGT3qHsVkrvclYMI5RfumGmVvgLpWUscv8k+ETmvmqjOdkugqB2Xzv1ggLsSpLbzi6+aWz7QVlzjNPeWZ33fQ8=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode-prod
    type: kubernetes.io/basic-auth
