---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAiA+MOL5K2Wz3foHp3dwawvPeOB1Eg9W6dwWJC5uU79KOLP6Sma9/KqkWHjJ1MIlFvpeU+Bmf0Yhb4Rdh3KPO/29QBP2Ta6NUrxiGSWtd623CKbwbYR2tbf33nLwlCztYQQb/Rp4Q+47sHH8iqF38ky+nJwDn3d9lRsqej03KBmAGfCMhwb51RGHbzTtOuVgdXjFOH6iT9rbSnH5OEvPaU6moxLc2y2SCbD0JHigS1RW9uvdUKDS6eVFeW9Gq9l7pFaxNqToomCEhUbhy9FL3ffAWmf2ndIxcdPpNwZm+AmyK8FpPrNahDyajqfaen8Rd956lAi4HELF/9jDRYGx+v8UDpgmXS/3cp75ha7+dZ0w9xLm0IJ9K0l8Uth31Mi2uJqs5mgKcfV6I5JuFzWc2XisFSUwiGthtNlIvqZ9PcT8Qz2P5LDSoNJ+OmNix0JUZcJoyfmeXsv6hT2wlWdQfMpiIuFuDFqIzu4egzmRNrcq4H99igdYaWUHsfi92UJpZyNHVi6nTDqNQqSiIEL1baMna9k1+9d+MO1C9DhrqBxv3NmL28xyn1Tzk3e5pTws8VOBSqq+2ixB9PURQHfSf57XxVrW6/yAocJmFtJqnFuoBgfat/u9KPq7SUVuafx6AMWj8VWQz3Duxl+KBHfHAac4N7j2P9J+YxpZTpwJM8otrXi0/IjJPGSVf43hz/fBpm/Po7BRxBouCMTTLH7N8MJACxZNw0P93nZQyS0egsuociuuStTT97pRdHrTQ3vVdLMVUOWSmFi/WyMKKGLDtFUt2acSfW7X6J1tEbA9Q6eZQGDO6MNlRItBn7caORDXrOPhiJ/uLvUbyxnMQyUqsJbX/z1JHYaRyFuRBponBvmqINNEWvu0Fwvol9pY6AaIb/6a3un2wRU5jNlEVEJRHLTC1+CtBey2EjZc0jHzdMsm9VGDNt
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-prod
    type: kubernetes.io/dockerconfigjson
