---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAS8FPNBbKrrx+QLBYTH2rruylRHmQT9DJ84LoI+AmfGlA15dMWfOeiUr8YlJEYPgkNq+tAPazDLz7Pyrv0/W/lteXpQJaW/7FrrEd2QT3Z0xme1R4Z4/2qIF3KWFhdWG/gI58ERWUNzElsqLEyGb0Mt6aO4nQjGgZ5X4Q9lhhMXFr+fEchQ4befMLMAyu7QJl/7x+l1YOw94FDfX8ECpKC4RwgstMRBt+YQWfixJfDUp/7I3PrEhJBsse3HhMNZz+hByDaMCUQ1s3iIiZyr02TS4ndGZgBLLaSzKccKzPD8gPNuezf1eh6uuJ0xgHsllEe2h5Aq0o5FIXASakHUIeKNKMYX4sfCRsdzkSjxsoM6wa2nfkzLBt5eAp7+UgdF95REDlR0G/HFQ4PbzDa0w4/hRxZg24wpFOMcIF4bsITqTMTTAvNpnHM8ufprCw1U9MBHxUL3IvjOLe+BWRaMdHZvzLiv9UcfwiOySJW1T5nXFg6T75ZHPSL09upSek8UL7jMAnhw/BVjFVLYoxdQ5Z5CPqZ8+q8xox4LhMc72aqORNINhfmnZSwBpPZCqQaIaV/OT0kz4Bi+x2ZtjKC8Pu2cl+pL9e8i2G6xRtRE47SmGvJYEU81mMVPad7j8Ae1h6eXDkA0kukVCLt7ASwmSDKQAeQYhAv3HTd0mPRkJbYS1y+Lm/rg2CK1nbyxBWJ17be9dC1tyZDEn2/URr5b8PTVwpSyXYUDtI=
    username: AgCapCRH9wnGv8XSWkilwnOAg8SAdrlcu03CTkuDG3y51auNPuQDexnavfNe07ShZw1usTP8siBZzbKeJ7KeiFTqj9k5wbbiW7UJga36+SFvAO8fERc0bkJmDcxxAz88s+VnVQZNo84tuLJsh9fuonigKmgj4bpHTuKlhrsoW6scxCMqcxKxgFWJLUUov7gKHTJxlEWd7PPsd952Y8hnaPP3oN6KfGBXFFGyAh4TLit9pQbq9Ttr7fQ+PFVdkhFHP9cpf/4qG3ksGtCFyOWTR0y3pkJH9S0GBLIyqC6UsICJqQqRzEYdEW7+dQpRHqA2aKG1nysKxWADB7fwKwLy+oqGSlv8oepSaEyv9ose8Uq7RFUBG7zN36e+1WtvjFCewRREVSEf9fjoZntOhSBFfgA+uSH+VeLkBLyN6O6NTzvgTN43UgQTqpe5FS/zAUhL50aQ+vOz5d/Z0SEnux051JFzqz46pDyf4aCvrUaMbHPF3Cl5sWBiPatSsF9TgLzYUTHah42AuFrTGypON12kEpE0uGL4OwFZDJgh+eZpgc6lWPz7zO1GA5ihVHtq6dSE09QwM+nTeRzhmkPEyoNuKVYItMokxew0gbB2BOmO39F6Jud1Frm81bkgnKDBf5xFVgD4DYl6YOuVLVaj1vTnfY04T1kENPk2lvxy14jMy4r1tZQNhmIuHFHNR4REGh/7bGRqvDU1+9qAYHYevvyTmNw=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode-dev
    type: kubernetes.io/basic-auth
