---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCgMEJdZHZsxcCEFqNhhkAwSoM6Mnzct53/UMcnQkUHmNZCmiPOqB9+1OTunjUmB9D6xcmJat4bXeo4jEBrh+urxXwQHuLul/0faOly6YV/HUDEf+gRTFUk5ICVgrGV/1/fuIphyEwgwxIi3UfItV5Z10lo7NXog42gKo3wHWVmJRjHQYQJAcmJxgp0QxE3CwHxwCNydd/bgjceOQ3ifZo4yzXwMbXMd2NUpwxw07tDwh9INFQ7SD+iZlwFtmgq8MBbT84N8EkEsRXLD9GqJ/7N2Mk7Z6vE32tEf4hTfWccqQwFjnTGk73+b3tSSSst/sWlIVe7StlhPqd2Bqn9FkhcfyFshjJJcYVGyz8+YKebCIqQyB6jHfxwdSPoKydNpdD7Dy/hS432YihkoHiPmo0quigSATIAu6TKZz2Zd5gOW7MZr7qOZ7WbluDHLF0UBFVuLBHR+zyanZgjP1CuNoVTKfO02f8emELzA9chJ5n0tTxejhfTjWhnGn8hSNBt+oWtypxPso6h21H6b4+Rb20VHT12xUqU3qwdppA9oKTxWX/sY05+eCCNZesHYkxpiJTTasQUpi2/iMdOPIfnZC3b1qAcXp2brzw7SRSlh8p2vF5JSxCGmWnNjCkUiuF9KH1q90OfJ4dQSKEjyRbQUjPTig0n2m9c0ikINYuBBvoTz40ICh3Twevp3UtWi/0e8MzJZIWjVjRjEZw+ItJHdsDddOYBW/Lcb73V5V7dFDoBIByER24GovfhhalxStAWecXq6jH8wNoAWkGxEoNDOLl98lLfSBOVUNQgbqQwlP05qj18HZibjYFQR2afU0me+H90U3EAUtapBR0Ux4AipdV1ip88SjU+cs0TT7+Tl27pRmfJWKGL0DTLYgN0hsvyP0ZA2pbFU9kCuheghSmXeUIqNJ7aPFyd71Mp05eyPJ/Qa+6TsVKQ
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
