---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCMRqhI6PLtWcbZGWRa8G79PD/5uoIEzraCO2eVyEKofea3W0cRbZsq89KnAOhngMHdY3Ik5Hci7Y/M28uElhWSVrGQYXWEThUxW17Mm3rBM7PZ1DNgUkiL4etFVVGdbkREJQwH9+4rQvU4FHG5heO9yVshknzqDqEyOOoSR+hZKRIUcDfg5uLQ8ULICr4UoddRtwqfsyeWnm7OdRbA1YOtdmu34SPCiIxsfnmbCotGTCd35Wr/VNauCbcc7C5720PZ4JIxR0/TeQDV3w8q8V2rNf1KWZPVTnR1Y2xV4bSfHW/ZOawNaysyxGKS5rRbtJpBYwU/Y0n5yfovyUPMgKKyJzAst91b/lRIlSoHw0bXR89xE5XmbeCVAU+Ye9ZCfK/rlgAMLCngS0R9o1sX84BhQJ0RFAhgUgltnykhJprjGuU/1e8VM8LMqEt29wqnVD3cnl5y0p99WW6wEU0+Exfem7MO0wY2T0pZqHLcTIaK+VugZarIQriD8C+Qxdh0hdO8+rJNG+A2inffrnuZkQaTvqngDWp6Wtq6NNqLXom8rt5R8b1NPKU78bFYF3sDaKL3xPpemzJKP3ALhFcdig+/KPLJMGCi4Zf2Wklxs09UKxo5vgw/UmTf9oufP75WcZTkcS2QIk75PFMjNRoI0mUhsoisb5oKTQ5HZV8HJiWAVcRMw1D0oMAuSfezDM4lTThO6rsoBemji9y8jOtgNsSRr2KhHB1fMZ01JX2JP3aljFwGttbbnvFoSiDjhkDptr85NQPtWdd/B82HlNQNQaXtzC3KONK81SrHq1QuU9a9BTKyf/cN3O6gWr3fWNG7oCXk0rvHo7Sm1+OA1qXlwXqrsk+MC51w4ZLLbFuvX4IEWY6NPLQ6nmCNLU02uMufkBz+/ZPXJCtPIInlGz6338qTHWpnWrT+FYv02fK3QyO7PlBgmiKe
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
