---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBMBjYq8HCQlHJVn94BWFd6eKI6VWME5oGrge+aIaZMxVAxDjxK+vfQYf95nJr7mZ0NjHAuWl0yBfGhYCEPrtDPoQCVedcYLBWsxkjljE97lqapU0IyXBdO/gRio461SGKBCi+pAGz6a2RBfNGeGj4cWon+whgAMSP266Ei/dnFC/8TlybJ65fHxHuR3megn694d8AL/wBB6rWNKAufuPYh9C2QYDpXaHmLozW9Kdi/qp+naINcFiR5YJlzWWLYl7PArVVyHFR3iwedCub0Yc8RXqTGZryeweUgzJ1u1wSEbV2K/k9csfltFAp4D1NqS9j9ydNkapqki3Lu0IrUYCkMbJxC7BIPNWhtKZt9GyYs9iEqSPB+G9X96umQxXGnuSYRPgy6670f7ksCD99zTr8a9HCZDPlaKRwKjZ53/Ptp3HSNc61aEPqQVZlmwLir6tToAHhNf7VCTpLnvxiddLnDdqwxDZV42pPLUJRu9/YxQ5WM5vOMHEN4Vd74o0law7QUrHbGXTskRgn7HyOnojfsPDtOjt52+buTyTihEw7prgKG8Wi3F2hdZGy6Tw9Ux+UUMIoU/n/uvWBTBFeKLmw96k2QKkeMxr4ZU4QdaDOalBiij0q62Si6uvB7H0LfABSQcKDiG2X5+q6YPkNbA6EeCGSdFoJopkonalP3Oiuu/duZ0qbLxzNZsZX4o68k3xekYHcG8/fY235W5fP2i/u9K+Sv7QhREokRE05tLpugbChmHaob5JKTlnsE1SybfA8PsGwy3Opx7u/NBgKD0lzmjMmiLm739y3WBe0WFDpPePner9psCrTNomWEgzCnUQXCl/DjwIZWQ3HcXU1+TheK4VPCCrwwlcSFD3dOzC2riKMFn1WhKfq1NboqsUteYJvU5iukGqxHuDMRsc4y/puGpwOZKJJct5aSgUUFHE1LFz8qMYme
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
