---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBA76U7m2pj6a1T/yFmEoQCdMIIgbeOeZKp8zp8G29HIMo42mzx/Vzbi+srUkDGgTEPW1+hW/7oUIRwXYgskAqZVBpq5hOSKT2ozeOGAPiIKHz1M+FI6x0EK+VkyRebXA1/TPwGbKFzd6pJ4WhOCywCx0BZ1J103GR+yTpjOtrUCQfMnClhFInI23sSvnKDYSaIckIeh8x+z2n88waaV5ZHqHecKkvVJJr6kYTkJinHRqRndt48PSRKP5iBw9EOb7x7XfmKbAANiOPnlbxnTP2ycE62Cbyx6SZ363klMEY8c1ZTj8A9Trvfww4V80BhV6QIVlwI508enIOhlv9FKBcGa4oDp/94H9rVTQxBUy3G3JxCksd0f3S2RCnSGNe/QExHLoF2mFU9A99boWxub1mm68KCyEjaXC2Ybw96SrvGYC+lhiSDWbUctDW2bmfFSe8ZiBkLM0VAO2WKsPgVBO3Q3Z67qwhCHFZhKnr/QG90IT4P8u4H9HWbrZu0/nPIEAxlczFllklXviF+Qa0SZXBNswNU2qo+1bCF8TlqkxTWXO112D7DrzdaCi21fsxdlunnGQ80MnpnxxpqN7SkOGXXDKYNeSWshKwfc4aSknmMmdqPeFLNMcgVG1vulKARYHGnq9ZuyqIRNJJQyz2tKYDDQy3MJYHKk+m6+d0OD5XJs7MIagftqbzuGIyRUrUMvdikdLB/mkOzyUx5eKw+dxXLUhxwBn2AUOyrgP8NnVtEn3RdM/2M7S/0Me6xwltb5po5xNG5QnbDRWw3pHENOsSpcXqo6GTRO9aGjWTR0YLhYirOByHlMfirR0YqkuVzHTH7vIM048fQnYOj3ac0kDNZLsWHTF7LIwc/e0TpE0G2VBMTnvJxVi9587nlJyc2dhh0yNhTgcJuppncbwlOUNcU8PYFvU4ruiHU21uk+oZB2yT50Xgv
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
