---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBCOOZdNjvhixuTXAf/Lifiao4nHpneyGaERhSWbxtlS/hwK12yH5hxPFAYCd59wg0q6LeQG+znmP1qC9NePXG5WM2ZigBnhQzwbCml1pRBdX8LDwlFeiArZzekb+cOutNv64fH+kRO4J99qcrnijBmnD9KmvRwcLL+Q67hkVesdpLQO1vzMQw5u0wmkv2+8V5PUb9Pl8W86+gNczPqPKm7CkiAhqv8dl1anwPb/LcQFz3n8a6ZIJWCIRvDRGlo7IDEW+0SN77aAu1W2tzfBTmgi1lt/LyVFeD0g+QaWo1WEEZ2ATTWKV0J76TdPrHJkYAAH/wTzpCnT0EG3WwSzZ5wAXOg0isn6GA43PQzJ10szW+B6cEkTyv3ScopfFV0LEkiy/XNDsVUPN76f5YNBK6LxxeDEJOZrAGP/6EPoTOvsSltogiC12yfZrTe/LTxvOkAABdMSea0MBAzTVNl6FOSlX47NsC0aPCNDfC9WAIzlfYpqw5In1d9jZKhD0CayaEULAVbxjRg9qWl+oBBPIj5WDFK1nCEiKSJxsk9StZouygkNv5fOHp9DvpetT2H8wT79SXUrDJuNYOlGH+HNUmtAazIj28mSn3xMPlYFc1eaDINsP7VnMjgVR8VfPuaFv12j3rRp3RIs2qPYS/fri6Q4SkN0elkHuCfN+7xwZbW3y28cdNLEpWn9M7QCYHr5oI7PMJvpNFJdjzdWA5GU6Lm4b8cA7vlbyNU3EhOAmY56FIgnZF1QMhNlSzRgLKVc5jDh1rC1VY61bTX0wHLn05+B3bCHYPlh1u1j4V2VOSmXP0JkXShIgNXyphpLdXNi5ebo2WhuyrTL3xsFQfd6ee+hMgpn51otzdQ54b1ortOw1MlOtH1hwTYLtkaMxZN6kd4ul+Calz22nr14zTreVrCvuCVtPT15ZKNP4+S6zFey4jp4/Xl
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
