---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAlBeOjGzkymqBuhK0A8STyEvgyjT2sU4Ai2GiDOW11oGakFAyxOS3+C/Ngo1rVtrUMEUNC4BnPJgy42bDKp5Jc/rSN+kCFHUoHBocs9+W0fHh/77UKbwYP+LLIQz4kIgf56joc8+SAn6otFZdLH05YM1WB0wptzw3K98QuO1FCvSNkqe04NoU9Si5RKUwbjt+/KmlZ5rTTVdXN04yIoGTk7OyKoTcnOPhmpifq2q0BbVYtd48IArkzft6o+Pq1KgoVTw8ik9Dz07xE7YNhBH+NT/SMHwu42YGPBK06giZvGtw4A9JYyMYQrDZWOGzC0ei7MKlKeMEiJx4PTcVeMqudIqOzrPDeRV41kpK+0gQq7c2117PiPc3KJop7oeTgukb/AE36IFMGf5PkDWcxnjQdxEgn+/OSCiBBbDDRl8KjntbloVVyvs4BcPE3bzERP8N1ZUtRptPiOPNfNbMa3q6i/B08fHHDcrxI2aJNmiMRvhPmSKwjBSjvAZqWq4b+DX3EScSJBLsZIevgRPQuflbS/mOQeL5nZnTyvD3FgWDb1yqAkZ8lbtn7o6sx7ity9KXZVpiEPYdMWI+zxzUufb0hgLSPg3KwxrE3+g+t+/9L6zIdYyzcLSNoSL2OCq/O0Emt9tCMH20pmmWK6/QZ40nsolkDzUi1uxeyNMCrNboS4OVJNmFAxYgIX9ffA27KeLApArUKuLqfEBYCOwsyxqaswXzx7K+04RTRYuWgHH/1F3DRkLtevmU5iJabCuuvrq6O9VDqs/8niLTKztp6CAWDkvLZnQaoFPAK4RhbKUReBq5RDdnDDDI36qAFXSK4EZiV5GsjBgewBAC3iHVs1vCqUoUsDFSdOpn5vxEv/uRtwrJ1puxaaN+RfGi5a0wHJ91iEgWWQuA3bcemF6e57T6bIgkQ163S1uoj0SUcOkknZi2DFmIx
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
