---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCImM8gX2lJOF2cy39qhEYMNFF3ITnF4Yopwa2ea0//B+/yxwu1gca04gRTgJAUuVpNpUrqANjftKtqYilgyzNSO7OdWKi84kngGG02HaLeRpW3d9TxMBcrP+S9V/WPoFuBYKxVHaCJT9Rmnr5yHW09qC5dyPaE+a+KejHY4Oweix4FaZKhrrNfKF/EPdIEat21BnTZ9reQE+mktJMuXERwVcOKXV6VgjMag60wDyR+8ZiNSG563BnZLS587HS/EXWVvJMqigEWHW2uwp5lQrDK4m6I86maJIgo3gW0hiiM3rECbD2Mja++MvFeehAoHjke/HkhH3TlgTGDea5gnEu5nPqamcS6WU6tOzgYZxapWYad7UKSOMKEs9Byxxxs8BQ6IQydBidDdXb8ey9p6uXLR+55zrIfKDmPY5cILNVdAsm1Zu3UgPLXwHPHmXpze+Z5dpIHrkNXcFclCDL09wXEvEV8cWY1Bbv2oT3Y62otcbaz1KX4PTWpAsZ2S3GwY8FE7BVlKJ49q+PXrvWKXvb5jDyqQcRhqQUtlDQ0Wgm0Wr7vLT6u0az7ZT/u65g/X9kfLKxCMvTdDAUCjY0C9KIcVp/q5GsdXA1k9WvKtQcqrIm9YbkA1CuCTSORQqrFkqSPZ6HoyRjP+TBiwuHK4y/YBAlFChle9e2tkyuat24HCfAuZGCnBYNojxcrJZZSaGPr0UeVnCLKd73RGQCpsMZKgFcGZ0vTttg=
    username: AgBtTspi6lvUpZJvBxQop6+cUY/xtLmPzk9vsKMxIlttJsZ6eA4rfib++FyeOF5VAapkyanu1aEcne50DjGO598AgGjvvaTAoxVNQcbCIae+8ohMQvgTMB9D2rO0hpbxnLFEmXqTa9gzPxenH34zumB2Ps74rb24ff7wBawEe+6yjZQMrWy2qKMX8AjS1v4Lk3C2zNr4xyI9OvMkXl0s99XpT8dBpsoeCrDEuaqldD0BTqiS8j3N24ygyeDrVDgCA+Z0mVpLDt2cIg6ICj+Kc0zVcCfEvFo+44rUDOGkK6yFm9zwsV0s5IZxSBIjjYTrQEeBcDOUePvPAUYt6zHgh5heRyRwZ5geyBgDJakOiepOTeeDrXJdRcIRIZv0VXG01pmDKuZJbtZ6elVCU4Q7ab1yvlAr1MjxY5lu1AxMWCxrbcvnOGOjF4efbbSJh4Nz0cnV2F5IAesoAz7o+IxcBIiMGh6Xm1OaqhSBVU69xmtpvMbycrP/AvaMySxh370/2eaflylfTlA3NgvQj6yL/G2sznJpegTlErL1nthQJP3sIfq779ygILM16SxZZNhPZpTOjTuo0+/V/k2Zhijt+13ADcMf8ZlZIRMiuauESfcr4XcajnYKqswjth7FR/mFPDTnPLq0GMenIyd5sA2yASVaQKgaFhmhVhdmOeQj5jjXOUV/C8vzsGUutBrxQReyT4lZOWgMHAUAXI3qY8Vkqbk=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode-dev
    type: kubernetes.io/basic-auth
