---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgB4YLhR3T89uYbDjVb/gMGWQHUbb7QCivEFHObyR0Al7N0iXTk7iVI+H7LmFXWJV7G5BVSix36RyHvSZKDs1o8/RTGNw7KiPFpM1HX/OcbwywxfVNUleW9niDQOAxn8Ajtr0u4qFYlCQe1apkxL+ykEs0graUNx1/5DkWBhz/wbH62/58fs0OMxWrf1z0PEe5wmrHLQMELOSPWNNkXlqnDnNeF6s3mNKAxFM+2kNmQpI3sDyl1OMp4UqVB3d/qhIVaJ9G9W89Og2+GZPGoTqLBvfhk5aZM8sJUQDCCcJBUccQ8XcgnyNpTiqhMpnRiRTeVdd7Ih/xnrVn8XSck3BXfRTdyxnmsQAFmCVWrfIOBkKvy9Ch+HcLMecsOEJTUA7VSQUY1nhHc19ZNTd0SscDFwA5ajMzKBuhyiYGKlCQO5ZxSHiFsLSVabE2RW1b3ks0iOoWp0lEWuuPa4X8/93ng7VApD6ITQUO3c7v9Yc3tc2MSjnKMSIFdNSYdsq8bUj4S0KzWDE/5K3Y95RTx+4X33AP/3WAbrpO2jEhqaFhO0YVvyZ0MVF+EFYGnaPGNN2+AbQ3WMAmewwseLFfYFbVWK/yQFNLMQwWPLTDChpaN9RZaTLxcecMiKzBi9vMsFlcFY43MwmqjIayX80ELNhIBn9IQblPi8oLCHCmxHa68jyLtKzRIPVvUXW+iqU6wexwxV/ht18vxlgJUHy9hgCznL8M1RxaX4Wm/9GwHOYSX1H64wSLaGMXzxmlUOeWTaZEOon7wMSmOh+Z+S2NwqTTXjG82H2Ie5tLyov8buxj3/Rhcmd/PlQAk2aUDVNhvmWL7Ut9jZcB/MQX/m04mbcctSHw/xL+WOjn2j2O4LI9sQORd9tiqpMBDsBJ48u6PCbCz2oDAVbA6RYnhcn5sNd2w2xYtnf6B7+aYeUPdK1ML3WwSPdwth
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
