---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBdBpzgHplL/ckP3R9fSdVvs5b6fvqk+J/Asa5hUZ/iKcapoGST5QXNmfvGqYFMbjTfefsz8avNMw/hqKJd6BHYWnv47qf3iONyD1JWThCN5ldqCO68Zx/PyX7UEP4flM54OHeYDmiacG+byxlmR5e/fEWnbY4Fwnfw8zG/SFLXOEO/ktEsh2+8e7Hk0SH8JZO+ZztnUI5DXipgIeG7Oo4+10JSL4DhNPs3GvdsJSi1x0R+C4DVyTC1GcBKs+7yLUJDilUWfVzPx3WbqqKXUh5uBm+2dUHHNcVZrHBDDShmS/U7eulZw6OMupsSIj5u4AZuDxjoRlj3+Wc79jIf84AUv+FxDgiEIX2+A0QjowGluc8W6WsBWuJbRlvp5s+qJ+IVGvVadERHik30/hCKbnzGCDjMFrueFt0vmy4Uh9Np3YaoJyCaV7KUSEDLIYtf3LNI4yT2OTkn81adAvnYfTsI68nWaeVfAARP14Oka/o1aQe1LAAS1kbVNbQmmQI4vHQrevTDMi2OTqZfh12A6iMGSRYFvdpi2ta++id1HeRUI1meLMQHc2uBAd7fIlzg+a3WKqpi1aUBiIrponW37DyYO6G8MisvIEUfOhmvOEV1pxtb3V2Pxj675QM3PUrZzeXO8FTWsACOp/OW9M6UkPqhpLKy7MEJwv9E/VMj5Eiq59L0UQrH5vExhdVkQXY92uEMJrX+pK/udbQ1iyQtsYTgQy7A667IdawmHjMoO9hNnF3oy2gRzMyl879YpBch+JP27ArZCcD+sapY/7A0syaqrCXRkw/ewTx3+K0aeRxYcAzgBEP1hi2WN4QDzGvhm3EQTEE8aIIzQuPdbgLNCXuJPOma5Z/m291OYe6oK+I9VeeNBvuP8CZ2TZmYavm+Zf3M8MAd5N10aTgNLzQLypcksW8PLqBN8JyQX9rz9n+6Um9xXEU0
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode-dev
    type: kubernetes.io/dockerconfigjson
