---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBtRieYL1aVmi6WjJCgW0cb1Du8J9Pl46H7lVkI/C6ECFXGuo/y1pQSVcc/rWCwWneQSV3mw9D8U/1tAX0q/WipaqkduySXtfLiKZqcwexO0Ceb0RtqgINC7jCE2W2mJpd3Py7oETyGw1ec7Wy+8unjWknCW3MFHRksJjFxpc4FNA9xgIGlOscegaJrDTa3rf2yDRAteIZv8Ba3+7YjHbLX+/1J7VwpW9Noqi1LYkSzVyWWyn6xSDXLtVxvM8COxPvzr6ZJt+2lCzJS0jTIkywt15wXICevT5o6baWuJB2UUQSZOlvWPZy3Zig8P1PPisM/SjeHkCb3zVVj3TF7RNnhyqOONu0T581jtjPphinlXmE5a2JKQDysa43zNzlVjRv5hIaESlxrJPeRVNUG49KhOkSvynS33xNmaSUR+d/NTGGCfHrG8g0eRrBWrTNOC45it1QEP1BPmJvcPyy0/u+u4nPhJMVoFNGP05syxhWqjfnc9EFazv60JvS3w77gusTmsWCdaNmJA9UWtD0kFNwex5xNPbxQP59RIO47XIfGY2+l9dj7WgB3WXg43cpQK8g0qiuNnZN4yebtQG75dyIeheKDoGKOdloXdrKviMPxxgRnhe83UOr9EYYDpiTfmD5qj8oT7ZJbXFNiJnuuexTdhDr6Oz7zACvw+69iiMqzysv0nSBwd+gIElET0jRrEn185TRuFdJ4/glYDipnqxCbRKXroUORUes=
    username: AgCMvjUPbvxKuRcJjoT6QhDA9JsNApRg4XITrMlVDL28nF7TdDt2wWbdoIHvtFSVcUlXbpF8CGJeYXI3pyYMIp3NaOwQXifnCTqrwVPL/MJu3GJ0J4aSssRMimhSu9GAQSIR9BbXTzPKHmT5jAFDmnv8xIEWUt1ByvoqTWRgcWiHQXl06IQFvF6UbuSmwsapPGSzkXkIqkGMMTzw+dIzBRqqxe3i1Po/hJq4BjamqJhTtr5WcSubFBnv3qd5gsRiIScByC50pjTPpct98f8jq/lfltksnmfly9Ke8ugUqOaMj4WaLr1vkn1BWaEvpOerc1NQLiGKLvsgtiKgQxWwSuL8kbIwzcUBBteacGIgnAbtDc6v2q4EJvfPgP1ohQ5SdrjPeIhi+BUocD2kqCYe8zxAh9DnrcW7eleiKJ2kE1xAs1b356xYtkfI8FEAKQb5Em0J9aTRkNU/RcJMGho9QLPLKgMP+tlB3I9eeQDrXkacfmzLNnYeFOhy2WrSYtWA9/cA/M9D1imYcK56Jz6uiQOB5e/27fDVB93GUt0XnJjxm0ap2KS8BOVAHzu840Y9cUsGdVu7sOtXtIhwDEAKQE6B9mYMal2r5DjhLtqMMOrLM4GZgERUU24ZIrH72ZpvPlwH6Vp3tivJ2bDVceUVCpnwqWhbc9TzYZEHfwBRWCjNZjW0ha5wqswYU5mfQ0SsUhbsr+cu+o7ReoA4OhaqPes=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode-dev
    type: kubernetes.io/basic-auth
