apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: musclecode-backend-main-service
  namespace: argocd
spec:
  project: musclecode
  source:
    kustomize:
      commonAnnotationsEnvsubst: true
    repoURL: 'https://github.com/ClaudiuBogdan/musclecode-backend-main-service'
    targetRevision: dev
    path: ./k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: musclecode-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
