apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: musclecode-backend-prod
  namespace: argocd
spec:
  project: musclecode
  source:
    kustomize:
      commonAnnotationsEnvsubst: true
    repoURL: https://github.com/ClaudiuBogdan/musclecode-backend-main-service
    targetRevision: main
    path: ./k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: musclecode-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 