apiVersion: apps/v1
kind: Deployment
metadata:
  name: musclecode-backend-main-service
  annotations:
    image-sha: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musclecode-backend-main-service
  template:
    metadata:
      labels:
        app: musclecode-backend-main-service
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: musclecode-backend-main-service
          image: harbor.devostack.com/musclecode/musclecode-backend-main-service:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: musclecode-backend-main-service-secrets
            - secretRef:
                name: musclecode-backend-main-service-secrets
            - configMapRef:
                name: musclecode-backend-main-service-config
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['image-sha']
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20

