apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: musclecode

resources:
  - deployment.yaml
  - service.yaml
  - sealed-secrets.yaml
  - prisma-migration.yaml

commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode
