apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
- postgres-deployment.yaml
- prisma-migration.yaml
- deployment.yaml
- service.yaml
- virtual-service.yaml

commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

patches:
- patch: |-
    - op: replace
      path: /spec/bootstrap/initdb/database
      value: musclecode
    - op: replace
      path: /spec/bootstrap/initdb/owner
      value: musclecode_user
  target:
    kind: Cluster
    name: postgres-db

images:
- name: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newTag: ed9f1125c722515a84485ba5cba59470a582b76f
commonAnnotations:
  image-sha: 67e9e107b614c05fce6fa3b44ed787c7ee70e14c
