apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
  - deployment.yaml
  - service.yaml
  - prisma-migration.yaml
  - postgres-deployment.yaml
  - secrets/sealed-registry-secret.yaml
  - secrets/sealed-db-secret.yaml
  - secrets/sealed-app-secret.yaml

commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

images:
  - name: $(DOCKER_REGISTRY_URL)/musclecode-backend-main-service
    newName: $(DOCKER_REGISTRY_URL)/musclecode-backend-main-service
    newTag: latest

replacements:
  - source:
      kind: Secret
      name: postgres-credentials
      fieldPath: data.POSTGRES_DB
    targets:
      - select:
          kind: Cluster
          name: postgres-db
        fieldPaths:
          - spec.bootstrap.initdb.database

  - source:
      kind: Secret
      name: postgres-credentials
      fieldPath: data.POSTGRES_USER
    targets:
      - select:
          kind: Cluster
          name: postgres-db
        fieldPaths:
          - spec.bootstrap.initdb.owner

  - source:
      kind: Secret
      name: musclecode-backend-main-service-secrets
      fieldPath: data.DOCKER_REGISTRY_URL
    targets:
      - select:
          kind: Deployment
          name: musclecode-backend-main-service
        fieldPaths:
          - spec.template.spec.containers.[name=musclecode-backend-main-service].image
      - select:
          kind: Job
          name: prisma-migrate
        fieldPaths:
          - spec.template.spec.containers.[name=prisma-migrate].image
