apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
- deployment.yaml
- service.yaml
- prisma-migration.yaml
- postgres-deployment.yaml
- ./secrets/sealed-app-secret.yaml
- ./secrets/sealed-db-deployment.yaml
- ./secrets/sealed-registry-secret.yaml

commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

images:
- name: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newTag: 9110c1c8c401f962554be192fda1bbb3f5c65b33

patches:
- target:
    kind: Cluster
    name: postgres-db
  patch: |-
    - op: replace
      path: /spec/bootstrap/initdb/database
      value: musclecode
    - op: replace
      path: /spec/bootstrap/initdb/owner
      value: musclecode_user
