apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
- deployment.yaml
- service.yaml
- prisma-migration.yaml
- postgres-deployment.yaml

commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

patches:
- patch: |-
    - op: replace
      path: /spec/bootstrap/initdb/database
      value: musclecode
    - op: replace
      path: /spec/bootstrap/initdb/owner
      value: musclecode_user
  target:
    kind: Cluster
    name: postgres-db

images:
- name: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newTag: b4a8894fee84b4a7677637a3845c046eb0bbb85d
commonAnnotations:
  image-sha: b4a8894fee84b4a7677637a3845c046eb0bbb85d
