apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode
resources:
- postgres-deployment.yaml
- prisma-migration.yaml
- deployment.yaml
- service.yaml
- virtual-service.yaml
- configmap.yaml
commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

patches:
- patch: |-
    - op: replace
      path: /spec/bootstrap/initdb/database
      value: musclecode
    - op: replace
      path: /spec/bootstrap/initdb/owner
      value: musclecode_user
  target:
    kind: Cluster
    name: postgres-db
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: musclecode-backend-main-service
    spec:
      template:
        metadata:
          annotations:
            image-sha: f3e74527b93f68c95337e03b4dbf37f64860c5a6
  target:
    kind: Deployment
    name: musclecode-backend-main-service
images:
- name: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newTag: f3e74527b93f68c95337e03b4dbf37f64860c5a6
