apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
- deployment.yaml
- service.yaml
- prisma-migration.yaml
- postgres-deployment.yaml
- secrets

commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

images:
- name: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newTag: 885df628368743ec6ae9f636d8e2fc01d9a1c67b
