apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
  - deployment.yaml
  - service.yaml
  - prisma-migration.yaml
  - postgres-deployment.yaml
  - secrets/sealed-registry-secret.yaml
  - secrets/sealed-db-secret.yaml
  - secrets/sealed-app-secret.yaml

commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

images:
  - name: harbor.devostack.com/musclecode/musclecode-backend-main-service
    newName: harbor.devostack.com/musclecode/musclecode-backend-main-service
    newTag: latest

replacements:
  - source:
      kind: Secret
      name: postgres-credentials
      fieldPath: data.POSTGRES_DB
    targets:
      - select:
          kind: Cluster
          name: postgres-db
        fieldPaths:
          - spec.bootstrap.initdb.database

  - source:
      kind: Secret
      name: postgres-credentials
      fieldPath: data.POSTGRES_USER
    targets:
      - select:
          kind: Cluster
          name: postgres-db
        fieldPaths:
          - spec.bootstrap.initdb.owner