apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode
resources:
- postgres-deployment.yaml
- prisma-migration.yaml
- deployment.yaml
- service.yaml
- virtual-service.yaml
- configmap.yaml
commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

patches:
- patch: |-
    - op: replace
      path: /spec/bootstrap/initdb/database
      value: musclecode
    - op: replace
      path: /spec/bootstrap/initdb/owner
      value: musclecode_user
  target:
    kind: Cluster
    name: postgres-db
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: musclecode-backend-main-service
    spec:
      template:
        metadata:
          annotations:
            image-sha: 61aa70c9d0db8fb0bc671b73b3d4071a6c068734
  target:
    kind: Deployment
    name: musclecode-backend-main-service
images:
- name: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newTag: 61aa70c9d0db8fb0bc671b73b3d4071a6c068734
