apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musclecode

resources:
- deployment.yaml
- service.yaml
- prisma-migration.yaml
- postgres-deployment.yaml
- ./secrets/sealed-app-secret.yaml
- ./secrets/sealed-db-deployment.yaml
- ./secrets/sealed-registry-secret.yaml

commonLabels:
  app.kubernetes.io/name: musclecode-backend-main-service
  app.kubernetes.io/part-of: musclecode

images:
- name: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newName: harbor.devostack.com/musclecode/musclecode-backend-main-service
  newTag: 5516860aae32a78b6890fe935a73b1b111f65d16
