apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: prisma-migrate
          image: harbor.devostack.com/musclecode/musclecode-backend-main-service:latest
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: musclecode-backend-main-service-secrets
      restartPolicy: Never
  backoffLimit: 3
