apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-musclecode-backend-main-virtualservice
  namespace: musclecode
spec:
  hosts:
    - "api.musclecode.devostack.com"
  gateways:
    - istio-system/istio-https-gateway

  http:
    - name: sse-stream
      match:
        - uri:
            prefix: "/"
          headers:
            accept:
              regex: "text/event-stream.*"
      route:
        - destination:
            host: musclecode-backend-main-service
            port:
              number: 80
      retries:
        retryOn: "5xx,connect-failure,refused-stream"
        attempts: 3
        perTryTimeout: 5s
      headers:
        request:
          set:
            Connection: "keep-alive"
            Accept: "text/event-stream"

    - name: default-route
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: musclecode-backend-main-service
            port:
              number: 80
      timeout: 300s                      
      retries:
        retryOn: "5xx,connect-failure"
        attempts: 3
        perTryTimeout: 2s
