---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
    argocd.argoproj.io/sync-wave: "-5"
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: musclecode
spec:
  encryptedData:
    password: AgCTDjUux5gwe5utb3fZ1DdeACAr59UxZvaui7iNvUTO+NOWDEPtXpewkjU+2ihY0tPcARwZiV92OuGYwwSbROEa4cRkmsK0YAYeCYO7wVUk+JsweOISnQvejKf0lk2AKgI794KeEXM6/WDB5EkIQbBPyjytOZ8SRDYoTUA15KOuaOToWJ4KQKXW6iM3+eSk227uXJtsOsd0n0XUiWfxWcUF2gM84ULU0n2ZLc2FFaJpR1BmzDIjp0SMwysKOudpEMfOvYSNzPF5HMsSgNfOYN82F38cV5RSYG0KxHaPS6c7zwXnTfTGDFX27yKQaXkFyVf25l3vQaLZiz7EtfbzisWXGDF2QNExYRonkD6XjA5omGA5WlxGidQn1n+0+tX64JB6o7XRAB0kU49Y7kiedXTrOUA7GIKz7shaVJmz3E4ryEqCmLdzqoG1cdDdLk8PVjq4RSiig7jOK5/QwmiczdqEDWH1IHhD88bcwcfV4UyXkPXnRlB23mhYfofiENQAf1N2TMKOFdui0XupDVBBtH9oT8FCxbfuZJKs28NBZDeRsLEtxCuHUIKqBDTNBEDJ3hBcG2tML10Jn5n2LQVeb/6NCvibqGUeGxgE0TVfikEqguFzPfrcoK9yffo6vJhtaWApk0F6F5kFENMhekMZpgPPOXejx3ACdESbfegKcFYWRF2xRdudOIXFJbeZwjSTQMrMVJruRtNCIieFfuwWpNRp4XqtES8x0Sg=
    username: AgA6m8cdh4rFbJrC60o+QTO0oHiFiA2+56gVqcjnDLDcvfWdQPq8QsWngItTbFM71X0shWft594ktnf6E2c2/HEaHKpCpktRgBHP0NHYYc80OvVW5HF1US1Qv7wWl42S5luQDVT8ECFzkItrXSuDd6Ae2I/Ovq5KKhzIYmxh5GGGZtGe/H4uodv/f8TIrihglFDnCu1HGvNReYupt2vwj/aP6uCwBnQiAJTbgbDEhFHsPe4D0YyUFCdL3bsq/yC5xu0IxfoZfuq1NKad29vIeJDvvOUIui7FZAvgmLSH5UEiS+/mBJnUMb9nS9GH6Ksv3EmcBD9to/O+xrrHneZ8v3Q55wHVPAW5rzeohylKvxaFaFtjeNfmIfY4KuVXY9qqnRWJiOd8ofBGqwkBhv8rrTB9eib5xd3Zs3pYt4ZRgYpTibAvzkU5F9KUAbtEWtOzs18zE11mMUnvjxPmNeqsCrHsF6eyjknoaD5isDYE5ebb1oMnO3PsIikxuNqPel+9Cgiwrf2Al4KfEvIDJE5GD1pVQeH10QInDr5IYWa0CPAWA+zOJZj+RGfk4Cawe+NXB79Hcg6DDfgWTkxx46w9t1+HpYCtP/Lk9Ua7MyKIQJ1XnU6j7wa3jkZclYj1u+V+Sw0Xnh51hLPTXs76H+k3a129wEFOmH7UqOYnPNDLji4L6/I/07nYxCsIOqvIEvU+KNU1/HKScL0a3RG1YDSR3/o=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: musclecode
    type: kubernetes.io/basic-auth
