---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode
spec:
  encryptedData:
    .dockerconfigjson: AgCDpylamZ1Y6LqScIhzfkqBj/NZeBu8aZUhxsoXYe/X6fQUmpagvFqCtQ95LGNgRahazbIyRTFZs+nmUmtX4/AB/YgakoWCjR9Gmt1RE1tolUZdn95tYziNt468VjSBCjYAMeKdNNTJxo+fS4edvOyGmthT87N9GH3tWMA3vHg1c0twUXZ1xLygln5yuogU3aRpd8gqRgV+PeKI2DgvKE22eRHvEptOKQEcknWFq6RvVlqLCTKJCIZQrzhBefcYnwuEWSv/vUq1bldV2WmvBLsl3RJaK7krzMnExai5Hl5pqqWNFz5LDuj1WV3HCG+hMVc+LYf6C8UJs/7HKUIGYvm0jaQCuq8nuz2gefC6FmVAvNPMU+ZnyYg+urdet9zc1kxSjWj5GB2rk3Rky2Ce91UMJ3juNuFlnSTvIGamuAX5mc2Du/C41HAinNMNtQJ4zTPNV1HjgnDiv7FXZVWR6IAchxhswtxGLNqPi5bTlqyKnUjWfiR2LJTAtiPmh1u/edg4bJjhd7kuQIr0pH6jvPAjOFCO5Gbngyc0j4Si+4H8LrsZn2q6UFkbdSuouCcHBR7m8R8DJRhYTGnxOVHdZ9v79cXKvoVWLnkurIQFcAs4LXGIvYAUesLvkKs4uhfG7d2PwBDZ3sH90TArNISjL9JYiDy4pVh4027nEFIaPcEMCCa3riUSNjqleM/7ZAzXh80dImg/5Mafg8eyHfRR02PhYwtu9n2YKKfF7bCnxfYEhnsoC+uZ7WyfTyDqZm5YbaMDUVMFzJPMj6WW3ITFm1Vkvr3sHGgsXJAuaVEkeNEdRVbigNulDCwCb83tTDqHiqysovR8FJT+8zJu6w56cUOI2GgVeEvZXSrijpprKw4eeSfpQ+x129dbwZKYKUKEFlbjs4eC2WGDfnCeI5pvW8/2pXrg5LF6WE0T75T3lJDccIDyLEIvU0RH8WcNgkR5TNM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode
    type: kubernetes.io/dockerconfigjson
