---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
    argocd.argoproj.io/sync-wave: "-5"
  creationTimestamp: null
  name: registry-credentials
  namespace: musclecode
spec:
  encryptedData:
    .dockerconfigjson: AgC6lgW4pC0DnoXwmtyuJVRpGll+cyBHbyPy4qCr3xXeao03e793Iu6fOg1RriFRBdon7s3xKChQ8lkEKzW8DuGtHhpP0yAmjwV+reX4kXVl34qGAULYowdUXyownWIWUmCCAX4TQHP90f3Kh/bldwILLssWpXsEAj2MLHcYQZE9wYY6pWGu8pf4ix5hPnHQLvS9lMBfxbVCX//cEVlZ85bKjXO9ZDi8qrkHcTWYLqahl0csJmdqhTAm4afRAWVVCV+XNpgcFvKw1Lb2I5cydconcDefrViKFARn7z7Dof1ImJwheesPkD1Gk5ND5V1SIKmq99C4nLIzgd5G5PnVLq+CCv9R05TY2zg+ObdPC5ar3F0zbpHBRrS2crhkenqIRpPUD2tJWjECQEekMHh86I8CyyfSUuCusOwpCVP8EFxi52NYUCl0aojvvljkgpuTycw/tvdnrbP26Kgf21CQhZHRwEOqNvdxFF5RPAh83/pkRD0wI1Lti7IMVxVsfwq61hSfJ4VO/HdQHaT+XTueKUZ6u1/eRTnXZf8MXGtuMzpP+HGUGPUybdb8G+p5AQs/JlHtSjuXKjpaSfXMzkU0dQAs+LRg3dwm9V+mMKxPVhtW9k7snMDDmAP5082hB650PfmiGVi3K/SttOXxQh2Xhr+3yMcHyPc5fhqO7Z2xqSLLUjFO9QjVUXOJx0FsPwauJvKbeCRzvOeAeX1kUzQ8fZ3gLuSU4KrFGDJdehLNoGg3YHWbYz+y1NrfaoWgnbkI7DJwBnNkCe2jnx8DnE+DlcVUFV5I2NzvURepQlhevwO/FYpYOOu9sKgAYZDKGJTZgFpNII5G/AyOPoPBy5khfSmbUNg2vKqW1rdBfyv2trBgnZzW0S6VLyPbr9cvOWZQ7LgD8GwaRuUON2vEm1n5mrQvommHF0SpxPs//GC9TeoRvLmLi4dk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: registry-credentials
      namespace: musclecode
    type: kubernetes.io/dockerconfigjson
