apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: musclecode-dev

resources:
  - ../../base
  - ./secrets/sealed-app-secret.yaml
  - ./secrets/sealed-db-deployment.yaml
  - ./secrets/sealed-registry-secret.yaml

patches:
  - target:
      kind: Cluster
      name: postgres-db
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-dev
      - op: replace
        path: /spec/storage/size
        value: 10Gi
      - op: replace
        path: /spec/bootstrap/initdb/database
        value: musclecode-dev
      - op: replace
        path: /spec/bootstrap/initdb/owner
        value: musclecode_user

  - target:
      kind: Deployment
      name: musclecode-backend-main-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-dev

  - target:
      kind: Service
      name: musclecode-backend-main-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-dev

  - target:
      kind: Job
      name: prisma-migrate
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: musclecode-dev
