name: Feature Branch Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO: add testing, linting, etc.
    
      - name: Get Secrets from Bitwarden
        uses: bitwarden/sm-action@v1
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            b964f6cf-76df-49cb-907a-b26600c5c7b8 > DOCKER_REGISTRY_URL
            5b1939aa-866f-4a3c-80b1-b26600c5f391 > DOCKER_USERNAME
            946357bf-ddfe-4de1-92a2-b26600c6cdc4 > DOCKER_PASSWORD
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY_URL }}/musclecode-backend-main-service:pr-${{ github.event.pull_request.number }} .
    